name: Sync Covers from Supabase

on:
  workflow_dispatch:
    inputs:
      files:
        description: "List of files (newline separated)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup folders
        run: mkdir -p b/cover/{0,1,2,3,4,5,6,7,8,9,misc}

      - name: Download files
        run: |
          echo "FILES:"
          echo "${{ inputs.files }}"

          while IFS= read -r file; do

            echo "Fetching $file"

            filename=$(basename "$file")
            base="${filename%.*}"
            last_digit="${base: -1}"

            if ! [[ "$last_digit" =~ ^[0-9]$ ]]; then
              last_digit="misc"
            fi

            curl -L \
              "https://euuptkidjsquvhohvicv.supabase.co/storage/v1/object/public/uploaded_cover/$file" \
              --output "b/cover/$last_digit/$filename"

          done <<< "${{ inputs.files }}"

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add b/cover/

          git commit -m "sync covers" || echo "no changes"
          git push
