name: Sync Covers from Supabase

on:
  workflow_dispatch:
    inputs:
      files:
        description: "List of files from Supabase"
        required: true
        type: string

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup folders
        run: |
          mkdir -p c/cover/{0,1,2,3,4,5,6,7,8,9}

      - name: Download files from Supabase Storage
        run: |
          echo "Downloading files..."

          for file in $(echo '${{ inputs.files }}' | jq -r '.[]'); do

            echo "Fetching $file"

            filename=$(basename "$file")

            # Endung entfernen
            base="${filename%.*}"

            # letzte Ziffer holen
            last_digit="${base: -1}"

            # falls keine Zahl -> misc
            if [[ ! "$last_digit" =~ ^[0-9]$ ]]; then
              last_digit="misc"
              mkdir -p "c/cover/misc"
            fi

            curl -L \
              "https://euuptkidjsquvhohvicv.supabase.co/storage/v1/object/public/uploaded_cover/$file" \
              --output "c/cover/$last_digit/$filename"

          done

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add c/cover/

          git commit -m "Sync covers" || echo "No changes"

          git push
