name: Sync Covers from Supabase

on:
  workflow_dispatch:
    inputs:
      files:
        description: "List of files from Supabase"
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup folders
        run: mkdir -p covers

      - name: Decode file list
        id: parse
        run: |
          echo '${{ inputs.files }}' > files.json
          cat files.json

      - name: Download files from Supabase Storage
        run: |
          echo "Downloading files..."

          for file in $(echo '${{ inputs.files }}' | jq -r '.[]'); do
            echo "Fetching $file"

            curl -L \
              "https://euuptkidjsquvhohvicv.supabase.co/storage/v1/object/public/uploaded_cover/$file" \
              --output "covers/$file"
          done

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add covers/

          git commit -m "Sync covers" || echo "No changes to commit"

          git push
